# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
